services:
  frontend:
    image: manacccc/tp2-2271627-2241112-frontend:${FRONTEND_VERSION:-latest}
    build:
      context: ./movies-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - movies-network

  backend:
    image: manacccc/tp2-2271627-2241112-backend:${BACKEND_VERSION:-latest}
    container_name: movies-backend
    build:
      context: ./movies-backend
    # In case you just want to deploy the backend and access it
    # without deploying the frontend, add a port mapping
    # ports:
    #   - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - movies-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_URL}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
      - SERVER_PORT=${API_PORT}

  mongodb:
    image: mongo:8.0.6
    networks:
      - movies-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - db:/data/db
      # ./mongo-seed folder contains a script to populate the database
      # this script will be copied inside the container and will run 
      # when the container starts
      - ./mongo-seed:/docker-entrypoint-initdb.d

volumes:
  db:

networks:
  movies-network:
    driver: bridge